alias jn="jupyter notebook"
alias srca="source activate"
alias e="acg-emacs"
alias mp3fromyoutube="youtube-dl --extract-audio --audio-format mp3 -l"
alias l="ls -CF1"
alias extravolume="pactl set-sink-volume 1 +10%"